Contact/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.Contact, name="Contact"),
    url(r'send/', views.Send),
]

Help/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.Help, name="Help"),
    url(r'^(?P<name>[А-Яа-я\s0-9-(),.?!/:;"#№$%*”+]+)/$', views.Question_category, name="Question_category"),
    # url(r'^search_results/(?P<name>[А-Яа-я\s0-9]+)/$', views.Search_results, name="Search_results"),
    url(r'find_help/(?P<text>[А-Яа-я\s0-9-(),.?!/:;"#№$%*”+]+)/$', views.Find_help, name="Find_help"),
    url(r'questions/(?P<text>[А-Яа-я\s0-9-(),.?!/:;"”#№$%*+]+)/$', views.questions, name="questions"),
    # url(r'^help_results/(?P<name>[А-Яа-я\s0-9]+)/$', views.Search_results_help, name="Search_results_help"),
    # url(r'^help_category/(?P<name>[А-Яа-я\s0-9]+)/$', views.Help_category, name="Help_category"),
    # url(r'^question_category/(?P<name>[А-Яа-я\s0-9]+)/$', views.Question_category, name="Question_category"),

    url(r'load_input_help', views.load_input_help, name='load_input_help'),
]

work/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'', include('Main.urls')),
    url(r'about/', include('About.urls')),
    url(r'category/', include('Category.urls')),
    url(r'help/', include('Help.urls')),
    url(r'contact/', include('Contact.urls')),
    url(r'news/', include('News.urls')),
    url(r'profile/', include('Profile.urls')),
    url(r'profile/advert/', include('Profile_advert.urls')),
    url(r'profile/task/', include('Profile_task.urls')),
    url(r'profile/offer/', include('Profile_offer.urls')),
    url(r'profile/balance/', include('Profile_balance.urls')),
    url(r'^profile/message/', include('Profile_message.urls')),
    url(r'^profile/notice/', include('Profile_notice.urls')),
    url(r'adverts/', include('Advert.urls')),
    url(r'tasks/', include('Task.urls')),
    url(r'profile/service/', include('Profile_services.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler413 = 'Main.views.handler413'

Contact/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
# Create your models here.
class Contact(models.Model):
    type = models.ForeignKey('ContactType', models.DO_NOTHING, blank=True, null=True, verbose_name="Тип контакта")
    name = models.CharField(max_length=100, blank=True, null=True, verbose_name="Текст")

    class Meta:
        managed = False
        db_table = 'contact'
        verbose_name = _("Контакт")
        verbose_name_plural = _("Контакты")


class ContactType(models.Model):
    name = models.CharField(max_length=50, blank=True, null=True, verbose_name="Наименование")

    class Meta:
        managed = False
        db_table = 'contact_type'
        verbose_name = _("Тип контакта")
        verbose_name_plural = _("Типы контактов")

    def __str__(self):
        return self.name


class Link(models.Model):
    link = models.CharField(max_length=100, blank=True, null=True, verbose_name="Ссылка")
    icon = models.CharField(max_length=100, blank=True, null=True, verbose_name="Иконка")

    class Meta:
        managed = False
        db_table = 'link'
        verbose_name = _("Ссылка")
        verbose_name_plural = _("Ссылки")


class City(models.Model):
    region = models.ForeignKey('Region', models.DO_NOTHING, blank=True, null=True, verbose_name="Регион")
    name = models.CharField(max_length=50, blank=True, null=True, verbose_name="Наименование")

    class Meta:
        managed = False
        db_table = 'city'
        verbose_name = _("Город")
        verbose_name_plural = _("Города")


class Region(models.Model):
    name = models.CharField(max_length=50, blank=True, null=True, verbose_name="Наименование")

    class Meta:
        managed = False
        db_table = 'region'
        verbose_name = _("Регион")
        verbose_name_plural = _("Регионы")

    def cities(self):
        city=City.objects.filter(region=self)
        return city

class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.BooleanField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.BooleanField()
    is_active = models.BooleanField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class Gender(models.Model):
    name = models.CharField(max_length=10, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'gender'


class Users(models.Model):
    auth_user = models.ForeignKey(AuthUser, models.DO_NOTHING, blank=True, null=True)
    phone = models.CharField(max_length=13, blank=True, null=True)
    city = models.ForeignKey(City, models.DO_NOTHING, blank=True, null=True)
    type = models.ForeignKey('UserType', models.DO_NOTHING, blank=True, null=True)
    uuid = models.CharField(max_length=50, blank=True, null=True)
    gender = models.ForeignKey(Gender, models.DO_NOTHING, blank=True, null=True)
    birthday = models.DateField(blank=True, null=True)
    about_me = models.CharField(max_length=5000, blank=True, null=True)
    get_new_order = models.BooleanField(blank=True, null=True)
    get_notice_status = models.BooleanField(blank=True, null=True)
    photo = models.ImageField(upload_to='uploads/users/', max_length=100, blank=True, null=True)
    verify_phone = models.BooleanField(blank=True, null=True)
    verify_passport = models.BooleanField(blank=True, null=True)
    passport_photo = models.ImageField(upload_to='uploads/users/', max_length=500, blank=True, null=True)
    verify_date = models.DateField(blank=True, null=True)
    passport_num_ser = models.CharField(max_length=50, blank=True, null=True)
    balance = models.IntegerField(blank=True, null=True)
    bonus_balance = models.IntegerField(blank=True, null=True)
    frozen_balance = models.IntegerField(blank=True, null=True)
    last_online = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'users'


class UserType(models.Model):
    name = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'user_type'

Contact/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
import json
from .models import *
from django.core.mail import send_mail


def layout_contact():
    contact=ContactType.objects.all()
    return contact
def layout_link():
    link=Link.objects.all()
    return link
def layout_regions_cities(request):
    city = request.session.get('city', 0)
    reg = request.session.get('reg', 0)
    regions = Region.objects.all()
    return city, reg,regions

def layout_name(request):
    layout = 'layout.html'
    username=''
    photo=''
    balance = 0
    bonus = 0
    user = request.session.get('username', 'no')
    if (user != 'no'):
        username=AuthUser.objects.all().filter(email=user)[0].first_name
        photo=Users.objects.all().filter(auth_user__email=user)[0].photo
        user = Users.objects.all().filter(auth_user__email=user)[0]
        balance = user.balance
        bonus = user.bonus_balance
        if (user.type.name == "Заказчик"):
            layout = 'layout_customer.html'
        else:
            layout = 'layout_executor.html'
    return layout, username, photo, balance, bonus

# Create your views here.
def Contact(request):
    layout, username, photo, balance, bonus = layout_name(request)
    contact = layout_contact()
    link = layout_link()
    city,regs,regions=layout_regions_cities(request)

    return render(request, 'Contact/Contact.html', locals())

def Send(request):
    name = request.GET.get("name")
    email=request.GET.get("email")
    theme=request.GET.get("theme")
    mes=request.GET.get("message")
    message='Имя пользователя - '+ name + '\n'
    message=message + 'Email - '+ email + '\n'
    message=message + mes
    if (theme == ''):
        send_mail('Обратная связь', message, 'romanenko.anastasiya1998@yandex.ua',
                  ['romanenko.anastasiya1998@yandex.ua'], fail_silently=False)
    else:
        send_mail(theme, message, 'romanenko.anastasiya1998@yandex.ua',
                  ['romanenko.anastasiya1998@yandex.ua'], fail_silently=False)
    return HttpResponse(json.dumps({'data': 'ok'}))

templates/Contact/Contact.html
{% extends layout %}
{% load staticfiles %}
{% block content %}
<div class="container-fluid p-0">
<div class="bg-map">
    <div class="bg-color-light w-100 h-100">
        <div class="bg-color w-100 h-100">
            <div class="row m-0 justify-content-center">
                <div class="col-12 col-sm-12 col-md-11 col-lg-10 col-xl-9 p-0 pt-3 pb-3">

                    <div class="row m-0 justify-content-center pb-4">
                         {% for ct in contact %}
                            {% if ct.name == "email" %}
                            <div class="col-12 col-sm-12 col-md-4 col-lg-4 col-xl-4 a-center pt-3 pb-3">
                                <i class="fas fa-envelope-open-text contact-icon"></i>
                                {% for c in ct.contact_set.all %}
                                    <label class="contact-text w-100 mb-0"><a href="mailto:{{c.name}}" class="contact-a">{{c.name}}</a></label>
                                {% endfor %}
                            </div>
                            {% else %}
                                {% if ct.name == "телефон" %}
                                <div class="col-12 col-sm-12 col-md-4 col-lg-4 col-xl-4 a-center pt-3 pb-3">
                                    <i class="fas fa-phone-alt contact-icon"></i>
                                    {% for c in ct.contact_set.all %}
                                        <label class="contact-text w-100 mb-0"><a href="tel:{{c.name}}" class="contact-a">{{c.name}}</a></label>
                                    {% endfor %}
                                </div>
                                {% else %}
                                    {% if ct.name == "время работы" %}
                                    <div class="col-12 col-sm-12 col-md-4 col-lg-4 col-xl-4 a-center pt-3 pb-3">
                                        <i class="fas fa-clock contact-icon"></i>
                                        {% for c in ct.contact_set.all %}
                                            <label class="contact-text w-100 mb-0">{{c.name}}</label>
                                        {% endfor %}
                                    </div>
                                    {% endif %}
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                    </div>

                    <div class="row justify-content-center align-items-center">
                        <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 a-center pt-3 pb-3">
                            <div class="row justify-content-center pb-4">
                                <h3 class="fw_700">Напишите нам</h3>
                            </div>
                            <div class="row justify-content-center">
                                <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-9 form-group">
                                    <input type="text" class="form-control" placeholder="Имя" id="name"/>
                                </div>
                                <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-9 form-group">
                                    <input type="email" class="form-control" placeholder="E-mail" id="email"/>
                                </div>
                                <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-9 form-group">
                                    <input type="text" class="form-control" placeholder="Тема сообщения" id="theme"/>
                                </div>
                                <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-9 form-group">
                                    <textarea name="" cols="30" rows="10" class="form-control" placeholder="Сообщение" id="message"></textarea>
                                </div>
                                <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-9 form-group">

                                <div class="alert alert-danger w-100" role="alert" style="display: none" id="alert-danger">
                                    Заполнены не все поля!
                                </div>
                                <div class="alert alert-success w-100" role="alert" style="display: none" id="alert-success">
                                    Сообщение успешно отправлено.
                                </div>
                                </div>
                                <div class="col-12">
                                    <button class="send-btn fz_12rem" id="send">Отправить</button>
                                </div>

                            </div>

                        </div>
                        <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 a-center pt-3 pb-3">
                            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2668.6972399698293!2d37.79851431588182!3d48.01955886735197!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40e0901357a3c079%3A0x6980cfa17d2d2f1c!2z0YPQuy4g0JDRgNGC0LXQvNCwLCAxMDIsINCU0L7QvdC10YbQuiwg0JTQvtC90LXRhtC60LDRjyDQvtCx0LvQsNGB0YLRjCwgODMwMDA!5e0!3m2!1sru!2sua!4v1573558526489!5m2!1sru!2sua" width="100%" height="400" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}